language: d
sudo: false

os:
  - linux
  - osx

matrix:
  include:
    - d: dmd-2.086.0
    - d: dmd-2.085.0
    - d: dmd-2.084.0
    - d: dmd-2.083.0
    - d: dmd-2.082.0
    - d: dmd-2.081.0
    - d: ldc-1.15.0
    - d: ldc-1.14.0
    - d: ldc-1.13.0
    - d: ldc-1.12.0
    - d: ldc-1.11.0

script:
  - dub test -b unittest-cov --compiler=${DC}
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
